blank_issues_enabled: true
contact_links:
  - name: Documentation (文档)
    url: https://github.com/NewFuture/DDNS/tree/master/doc
    about: Check the documentation for help (查看文档获取帮助)
  - name: Discussions (讨论区)
    url: https://github.com/NewFuture/DDNS/discussions
    about: Ask questions and discuss ideas (提问和讨论想法)
